"""empty message

Revision ID: 401d7082bf10
Revises: 379e253a62b0
Create Date: 2024-05-24 13:19:56.451853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401d7082bf10'
down_revision = '379e253a62b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classe', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etd', schema=None) as batch_op:
        batch_op.drop_column('classe')

    # ### end Alembic commands ###
